# Generated by Django 4.2.7 on 2023-12-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_category_remove_task_status_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='task',
            field=models.ManyToManyField(to='tasks.task'),
        ),
    ]
