# Generated by Django 4.2.7 on 2023-12-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
    ]
